name: App python teste

# Trigger (gatilho)
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configurar ambiente para o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2
        
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Executar testes
        run: |
          coverage run -m app_test
          
      - name: Resultados
        run: coverage report

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Verificar login no Docker Hub
        run: docker info

      - name: Build Docker image
        run: docker build -t henriquelucareli/projeto_desafio:latest .

      - name: Push Docker image
        run: docker push henriquelucareli/projeto_desafio:latest
